# Generated by Django 6.0.4 on 2026-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientAge',
            field=models.IntegerField(default=18),
        ),
    ]
