# Generated by Django 6.0.4 on 2026-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='badgeNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
