# Generated by Django 6.0.4 on 2026-05-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_couponcode_equipment_pricing_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
    ]
