# Generated by Django 6.0.4 on 2026-05-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_couponcode_percentage_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='LiveStatus',
        ),
    ]
