# Generated by Django 6.0.4 on 2026-05-30 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_receptionist_email_receptionist_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='payee',
            new_name='payed',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='details',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_checkin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_checkout',
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stayhistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stayHistory', to='interface.client'),
        ),
    ]
